---
deployment:
  tasks:
    - export DEPLOYPATH=/home/abenezerkifle000@gmail.com/home
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /usr/local/bin/npm install --production --prefix $DEPLOYPATH
    - /usr/local/bin/npm run build --prefix $DEPLOYPATH
